#pragma once

enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN ,DIR_END};
enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_ITEM, OBJ_SPIKE, OBJ_POINT, OBJ_SPRING, OBJ_UI, OBJ_END };
enum SCENEID { SC_LOGO, SC_MENU, SC_EDIT, SC_STAGE, SC_END };
enum TILEID {TILE_NORMAL, TILE_SLIDE, TILE_SLIDEUP, TILE_CIRCLE, TILE_END };
enum GRAVITY_STATE { DOWN_VERTICAL, UP_VERTICAL, RIGHT_HORIZIONAL, LEFT_HORIZIONAL, GRAVITY_END };
